name: Setup Node.js Project
description: Checkout code, setup Node.js, and install dependencies

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci
